# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-21 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organization', '0005_auto_20180621_1331'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacher',
            name='image',
            field=models.ImageField(null=True, upload_to='teacher/%Y/%m', verbose_name='\u5934\u50cf'),
        ),
    ]
