# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2018-06-17 15:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180612_1140'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailverifyrecord',
            name='is_rcode',
            field=models.BooleanField(default=False),
        ),
    ]
